# Generated by Django 3.1.3 on 2021-10-13 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddata',
            name='fertility_window',
        ),
        migrations.CreateModel(
            name='FertilityWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertility_window', models.DateField()),
                ('processed_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodapi.processeddata')),
            ],
        ),
    ]
