# Generated by Django 3.1.3 on 2021-10-13 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodapi', '0002_auto_20211013_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processeddata',
            old_name='period_end_data',
            new_name='period_end_date',
        ),
    ]
