# Generated by Django 3.1.3 on 2021-10-13 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodapi', '0003_auto_20211013_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddata',
            name='raw_data',
        ),
    ]
