# Generated by Django 3.1.3 on 2021-10-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodapi', '0004_remove_processeddata_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilitywindow',
            name='processed_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertility_window', to='periodapi.processeddata'),
        ),
    ]
